// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hokxdvywxbbmixqxvxie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhva3hkdnl3eGJibWl4cXh2eGllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTQ4MTUsImV4cCI6MjA2OTc3MDgxNX0.Q5iNkVG26LtLjirzlruDEuIQGttHhmMu0XhiUQtFfYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});